#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1/

traits:
  - securedBySteroidsApiKey:
      headers:
        steroidsApiKey:
          type: string
          example: exampleapikey
          default: 85ff112a7769331af36adec68b890b9118f0615d0e849f7e3146b24eb7622f53
        steroidsAppId:
          type: integer
          example: 1234
          default: 62315

schemas:
  - user_collection: '{"$schema":"http://json-schema.org/schema","title":"user collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical user representation","properties":{"username":{"type":"string"},"name":{"type":"string"},"email":{"type":"string"},"phone":{"type":"string"},"password":{"type":"string"}},"required":[]}}}}'
  - user_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical user representation","properties":{"object":{"type":"object","properties":{"username":{"type":"string"},"name":{"type":"string"},"email":{"type":"string"},"phone":{"type":"string"},"password":{"type":"string"}},"required":[]}}}'
  - request_collection: '{"$schema":"http://json-schema.org/schema","title":"request collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical request representation","properties":{"title":{"type":"string"},"content":{"type":"string"},"poster":{"type":"string"},"personen":{"type":"integer"},"categorie":{"type":"string"}},"required":[]}}}}'
  - request_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical request representation","properties":{"object":{"type":"object","properties":{"title":{"type":"string"},"content":{"type":"string"},"poster":{"type":"string"},"personen":{"type":"integer"},"categorie":{"type":"string"}},"required":[]}}}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:


/user:
  description: |
    {
      "resourceName": "user",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member

/request:
  description: |
    {
      "resourceName": "request",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member


